### ISSUE TITLE
[Bug] v7 is incompatible with react-map-gl-draw 1.0.3

### ISSUE THREAD

**Issue by engelzero** [visgl/react-map-gl#1969]
### Description

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'Consumer')

### Steps to Reproduce

    "react-map-gl": "^7.0.17",
    "react-map-gl-draw": "^1.0.3",

```
mode-handler.js?c23f:685 Uncaught TypeError: Cannot read properties of undefined (reading 'Consumer')
    at Editor.render (mode-handler.js?c23f:685:1)
    at finishClassComponent (react-dom.development.js?ac89:17485:1)
    at updateClassComponent (react-dom.development.js?ac89:17435:1)
    at beginWork (react-dom.development.js?ac89:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at beginWork$1 (react-dom.development.js?ac89:23964:1)
    at performUnitOfWork (react-dom.development.js?ac89:22776:1)
    at workLoopSync (react-dom.development.js?ac89:22707:1)
    at renderRootSync (react-dom.development.js?ac89:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js?ac89:22293:1)
    at eval (react-dom.development.js?ac89:11327:1)
    at unstable_runWithPriority (scheduler.development.js?bcd2:468:1)
    at runWithPriority$1 (react-dom.development.js?ac89:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js?ac89:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js?ac89:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js?ac89:21893:1)
    at dispatchAction (react-dom.development.js?ac89:16139:1)
    at eval (map.js?48e9:65:1)
render @ mode-handler.js?c23f:685
finishClassComponent @ react-dom.development.js?ac89:17485
updateClassComponent @ react-dom.development.js?ac89:17435
beginWork @ react-dom.development.js?ac89:19073
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
beginWork$1 @ react-dom.development.js?ac89:23964
performUnitOfWork @ react-dom.development.js?ac89:22776
workLoopSync @ react-dom.development.js?ac89:22707
renderRootSync @ react-dom.development.js?ac89:22670
performSyncWorkOnRoot @ react-dom.development.js?ac89:22293
eval @ react-dom.development.js?ac89:11327
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?ac89:11322
flushSyncCallbackQueue @ react-dom.development.js?ac89:11309
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21893
dispatchAction @ react-dom.development.js?ac89:16139
eval @ map.js?48e9:65
Promise.then (async)
eval @ map.js?48e9:44
invokePassiveEffectCreate @ react-dom.development.js?ac89:23487
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
flushPassiveEffectsImpl @ react-dom.development.js?ac89:23574
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
flushPassiveEffects @ react-dom.development.js?ac89:23447
performSyncWorkOnRoot @ react-dom.development.js?ac89:22269
eval @ react-dom.development.js?ac89:11327
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?ac89:11322
flushSyncCallbackQueue @ react-dom.development.js?ac89:11309
unbatchedUpdates @ react-dom.development.js?ac89:22438
legacyRenderSubtreeIntoContainer @ react-dom.development.js?ac89:26020
hydrate @ react-dom.development.js?ac89:26086
renderReactElement @ index.js?46cb:423
doRender @ index.js?46cb:709
_callee$ @ index.js?46cb:316
tryCatch @ runtime.js?ecd4:45
invoke @ runtime.js?ecd4:274
prototype.<computed> @ runtime.js?ecd4:97
asyncGeneratorStep @ _async_to_generator.js?0e30:23
_next @ _async_to_generator.js?0e30:12
eval @ _async_to_generator.js?0e30:17
eval @ _async_to_generator.js?0e30:9
_render @ index.js?46cb:334
render @ index.js?46cb:307
_callee$ @ index.js?46cb:302
tryCatch @ runtime.js?ecd4:45
invoke @ runtime.js?ecd4:274
prototype.<computed> @ runtime.js?ecd4:97
asyncGeneratorStep @ _async_to_generator.js?0e30:23
_next @ _async_to_generator.js?0e30:12
Promise.then (async)
asyncGeneratorStep @ _async_to_generator.js?0e30:32
_next @ _async_to_generator.js?0e30:12
Promise.then (async)
asyncGeneratorStep @ _async_to_generator.js?0e30:32
_next @ _async_to_generator.js?0e30:12
Promise.then (async)
asyncGeneratorStep @ _async_to_generator.js?0e30:32
_next @ _async_to_generator.js?0e30:12
Promise.then (async)
asyncGeneratorStep @ _async_to_generator.js?0e30:32
_next @ _async_to_generator.js?0e30:12
eval @ _async_to_generator.js?0e30:17
eval @ _async_to_generator.js?0e30:9
_hydrate @ index.js?46cb:304
hydrate @ index.js?46cb:193
eval @ next-dev.js?3515:40
Promise.then (async)
eval @ next-dev.js?3515:35
./node_modules/next/dist/client/next-dev.js @ main.js?ts=1662205943392:500
options.factory @ webpack.js?ts=1662205943392:713
__webpack_require__ @ webpack.js?ts=1662205943392:37
__webpack_exec__ @ main.js?ts=1662205943392:1239
(anonymous) @ main.js?ts=1662205943392:1240
webpackJsonpCallback @ webpack.js?ts=1662205943392:1298
(anonymous) @ main.js?ts=1662205943392:9
Show 26 more frames
next-dev.js?3515:20 The above error occurred in the <ModeHandler> component:

    at Editor (webpack-internal:///./node_modules/react-map-gl-draw/dist-es6/editor.js:86:5)
    at div
    at eval (webpack-internal:///./node_modules/react-map-gl/dist/esm/components/map.js:46:81)
    at MapView (webpack-internal:///./src/components/Mapbox/MapView.tsx:78:63)
    at div
    at div
    at Example (webpack-internal:///./src/pages/app/map.tsx:20:62)
    at EnvironmentProvider (webpack-internal:///./node_modules/@chakra-ui/react-env/dist/chakra-ui-react-env.esm.js:120:24)
    at ColorModeProvider (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/chakra-ui-color-mode.esm.js:222:21)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-6a883da9.browser.esm.js:96:64)
    at ThemeProvider (webpack-internal:///./node_modules/@chakra-ui/system/dist/chakra-ui-system.esm.js:70:27)
    at eval (webpack-internal:///./node_modules/@chakra-ui/hooks/dist/chakra-ui-hooks.esm.js:285:23)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/provider/dist/chakra-ui-provider.esm.js:24:24)
    at AuthWrapper (webpack-internal:///./src/components/Layouts/AuthWrapper.tsx:15:22)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:63:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:20740)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:8:23632)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:71:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:588:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:699:27)

```

**Comment by Pessimistress** [comment]
This breakage is intentional in order to support Mapbox official plugins, see https://visgl.github.io/react-map-gl/docs/upgrade-guide#upgrading-to-v70

Example using react-map-gl with mapbox-gl-draw is at https://visgl.github.io/react-map-gl/examples/draw-polygon

I see that you have found #1892. Please do not open duplicate issues. If you need help upgrading, use Discussions.
