### ISSUE TITLE
[Bug] onMouse events querying features when map has not yet finished loading

### ISSUE THREAD

**Issue by mattacus** [visgl/react-map-gl#2043]
### Description

When moving the mouse in the map layer before it has finished loading, I see the following stack trace in the console fired repeatedly (based on the mouse movement events):

```
Error: The layer 'clusters' does not exist in the map's style and cannot be queried for features.
    at ei.queryRenderedFeatures (style.js:1341:1)
    at Map.queryRenderedFeatures (map.js:1721:1)
    at Mapbox._updateHover (mapbox.ts:795:1)
    at Mapbox._onPointerEvent (mapbox.ts:823:1)
    at Map.fire (evented.js:128:1)
    at Mapbox._fireEvent (mapbox.ts:876:1)
    at dr.mousemove (map_event.js:129:1)
    at $r.handleEvent (handler_manager.js:376:1)
```

This appears to happen only when I provide a callback to the map component for one of these three functions:

- onMouseEnter
- onMouseLeave
- onMouseMove

### Expected Behavior

I would expect there to be some way to have the event not propogate to the default mapbox functions and query layers that have not rendered yet.  I have tried `event.preventDefault()`, and `event.stopPropagation()` in the callback handler, without success.

### Steps to Reproduce

1. Create a map with a source and layers that take a moment to render
2. Add a handler for one of the three mouse event functions above
3. Render the map and mouse around the map area while it is loading in
4. Observe the error(s) in the console for the layers/features that have not loaded yet

### Environment

- Framework version: react-map-gl@7.0.19
- Map library: mapbox-gl@2.10.0
- Browser: Chrome 107
- OS: Win 11

**Comment by mattacus** [comment]
🥳
