### ISSUE TITLE
[Bug] Fog & marker issue - getOpacityAtLatLng

### ISSUE THREAD

**Issue by elvince** [visgl/react-map-gl#2337]
### Description

When loading the map, I have a marker defined in the map component.
For any reason, I have an error that is thrown in getOpacityAtLatLng.
When looking at the error, it is something for Fog but I set the fog to undefined in the Map component.
It seems that this prop is set on the map-gl component and a default fog is present.

error:
```
Cannot read properties of undefined (reading 'get')
 at get state (d:\workspaces\MetaFlightApp\main\MetaFlightapp\node_modules\mapbox-gl\src\style\fog.js:58:9)
    at getOpacityAtLatLng (d:\workspaces\MetaFlightApp\main\MetaFlightapp\node_modules\mapbox-gl\src\style\fog.js:112:16)
    at _queryFogOpacity (d:\workspaces\MetaFlightApp\main\MetaFlightapp\node_modules\mapbox-gl\src\ui\map.js:2757:9)
    at _evaluateOpacity (d:\workspaces\MetaFlightApp\main\MetaFlightapp\node_modules\mapbox-gl\src\ui\marker.js:458:13)
```

thanks for the help

### Expected Behavior

No error

### Steps to Reproduce

I can't get a simple sample to provide for repro this bug.

### Environment

- Framework version: react-map-gl@7.1.6
- Map library: mapbox-gl@2.7.14
- Browser: electron
- OS: win10

**Comment by Pessimistress** [comment]
We are unable to reproduce your issue with the provided information. Feel free to reopen if you can get a repro.

**Comment by april-property** [comment]
Hi @elvince I am wondering if you have resolved the bug? I am experiencing the same issue but cannot pinpoint the exact cause of it.
